name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'master' }}
    steps:
    - uses: Swatinem/rust-cache@v2
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
    - uses: taiki-e/install-action@v2
      with:
        tool: just,wasm-pack
    - name: Build
      run: |
        just build
    - name: Upload artifact
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: dist/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
